### ISSUE TITLE
Question about Goodix Fingerprint

### ISSUE THREAD

**Issue by DeckerSU** [DroidThug/android_device_letv_x3#1]
Do you have working Goodix Fingerprint on CM builded on this tree? Now i'm have a device with MT6755 CPU and same fingerprint and have a little problem. Seems all blobs and sepolicy are fine, if launch any app to test finger - seems it works, vibrate and read finger. But i can't add any fingers through standart Settings menu. It crashes:

	03-07 18:09:43.197  3503  3503 D AndroidRuntime: Shutting down VM
	03-07 18:09:43.199  3503  3503 E AndroidRuntime: FATAL EXCEPTION: main
	03-07 18:09:43.199  3503  3503 E AndroidRuntime: Process: com.android.settings, PID: 3503
	03-07 18:09:43.199  3503  3503 E AndroidRuntime: java.lang.NullPointerException: Attempt to write to field 'int android.app.Fragment.mNextAnim' on a null object reference
	03-07 18:09:43.199  3503  3503 E AndroidRuntime: 	at android.app.BackStackRecord.run(BackStackRecord.java:780)
	03-07 18:09:43.199  3503  3503 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
	03-07 18:09:43.199  3503  3503 E AndroidRuntime: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
	03-07 18:09:43.199  3503  3503 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
	03-07 18:09:43.199  3503  3503 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
	03-07 18:09:43.199  3503  3503 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
	03-07 18:09:43.199  3503  3503 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6126)
	03-07 18:09:43.199  3503  3503 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
	03-07 18:09:43.199  3503  3503 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	03-07 18:09:43.199  3503  3503 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
	03-07 18:09:43.200   860  2059 I am_crash: [3503,0,com.android.settings,952647237,java.lang.NullPointerException,Attempt to write to field 'int android.app.Fragment.mNextAnim' on a null object reference,BackStackRecord.java,780]

Seems this happens in com.android.settings/.fingerprint.FingerprintEnrollEnrolling. Before i add finger :( In your build it works?

**Comment by DroidThug** [comment]
Same here. We had to restore the enrolled fingerprint data from stock.. I'll look into this and report back

**Comment by DeckerSU** [comment]
I think i get a solution ... but need some time to test. Fingers now enrolls correctly and added to base. But seems there is some problem, it doesn't recognize at lock screen. I will write here after some tests about a solution. BTW, where is enroleed fingerprint data is located on stock? I found an XML /data/system/users/0/settings_global.xml with fingers ID, but there is other data located?

**Comment by SscSPs** [comment]
data/app/mcRegistery @DeckerSU

**Comment by SscSPs** [comment]
https://youtu.be/lT6mEh2S-9c?t=12m25s
check this video, you can just mute it if you don't understand Hindi.
the process it till 19.00 to make the backup file for fingerprint data stored with stock

**Comment by DeckerSU** [comment]
Heh ... more troubles coming ... fingers really stored in **/data/app/mcRegistry/TbStorage**, but here another trouble. PackageManager in Lineage see that /data/app/mcRegistry doesn't contain base **apk** and killing that folder:

```
03-08 22:34:34.110   633   633 W PackageManager: Destroying /data/app/mcRegistry due to: android.content.pm.PackageParser$PackageParserException: Missing base APK in /data/app/mcRegistry
03-08 22:34:34.110   633   633 I pm_critical_info: Destroying /data/app/mcRegistry due to: android.content.pm.PackageParser$PackageParserException: Missing base APK in /data/app/mcRegistry
```

Seems need to patch PackageManager in Lineage too ... working ... after i complete all - will post a solution.
