### ISSUE TITLE
Camera build flags

### ISSUE THREAD

**Issue by DeckerSU** [DroidThug/android_device_letv_x3#3]
Another question to @DroidThug  about Camera. As i see you use in your tree many camera-related flags, but most of them don't use in Lineage sources. For example:

USE_MTK_CAMERA_WRAPPER := true - this is don't used, it uses by Camera Wrapper by @danielhk [here](https://github.com/danielhk/android_device_lenovo_aio_otfp/tree/cm-14.1/camera_wrapper), but as i see in this tree don't use any camera wrapper source.

TARGET_HAS_LEGACY_LP_CAM - is also not standart LineageOS 14.1 flag too. As a previous here it doesn't affect anything in build.

**Main question:** have you working camera in your buid? Or sometimes see stack crash when call to ACDK_SENSOR_RESOLUTION_INFO_STRUCT in mgSensorDrv::getResolution() (see description of this error [here](https://forum.xda-developers.com/k3-note/orig-development/rom-custom-nougat-roms-k-3-note-t3513466)). If all working - do you use any specific LIBC build flag?

**Comment by SscSPs** [comment]
He added a bunch of code to try to fix cam

**Comment by WisniaPL** [comment]
@DeckerSU Camera doesn't work. All libs are included.. Maybe you know how to solve it?
```
I/CameraManagerGlobal( 2940): Connecting to camera service
E/CameraService(  400): getCameraVendorTagDescriptor: camera hardware module doesn't exist
D/AndroidRuntime( 2940): Shutting down VM
E/AndroidRuntime( 2940): FATAL EXCEPTION: main
E/AndroidRuntime( 2940): Process: org.cyanogenmod.snap, PID: 2940
E/AndroidRuntime( 2940): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.cyanogenmod.snap/com.android.camera.CameraActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/AndroidRuntime( 2940): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
E/AndroidRuntime( 2940): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
E/AndroidRuntime( 2940): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/AndroidRuntime( 2940): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
E/AndroidRuntime( 2940): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2940): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 2940): 	at android.app.ActivityThread.main(ActivityThread.java:6126)
E/AndroidRuntime( 2940): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2940): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/AndroidRuntime( 2940): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/AndroidRuntime( 2940): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/AndroidRuntime( 2940): 	at com.android.camera.util.CameraUtil.isCamera2Supported(CameraUtil.java:386)
E/AndroidRuntime( 2940): 	at com.android.camera.CameraActivity.onCreate(CameraActivity.java:1513)
E/AndroidRuntime( 2940): 	at android.app.Activity.performCreate(Activity.java:6679)
E/AndroidRuntime( 2940): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
E/AndroidRuntime( 2940): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
E/AndroidRuntime( 2940): 	... 9 more
```

**Comment by iocmet** [comment]
Well, this issue is 6 years old but i have same issue with custom LineageOS 14.1 build, it just says connecting to camera service and then camera hardware module doesnt exist
